# Generated by Django 3.1 on 2020-08-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaposts', '0005_auto_20200810_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='post_id',
        ),
    ]
