# Generated by Django 3.1 on 2020-08-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaposts', '0006_auto_20200810_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
